Album album1 = new Album();
album1.Title = "Demon Days";
album1.Band = "Gorillaz";
Song song1 = new Song();
song1.Title = "Intro";
song1.Band = "Gorillaz";
song1.Duration = 63;
song1.PlayCount = 1;
song1.Favorite = false;
Song song6 = new Song();
song6.Title = "Feel Good Inc.";
song6.Band = "Gorillaz";
song6.Duration = 222;
song6.PlayCount = 100;
song6.Favorite = true;
album1.AddSong(song1);
album1.AddSong(song6);
album1.DisplaySongList();
album1.DisplayAlbumDetails();